import mongoose, { Schema, Document, Model } from "mongoose";

// Interface for a single chat
interface IChatItem {
  chatId: string;
  title: string;
  model: number; // 0 for GPT-3.5, 1 for GPT-4
  createdAt?: Date; // Optional since default is set
}

// Interface for the user chats document
interface IUserChats extends Document {
  userId: string;
  chats: IChatItem[];
  createdAt?: Date; // Auto-generated by Mongoose
  updatedAt?: Date; // Auto-generated by Mongoose
}

// Define the schema for the chat model
const userChatsSchema: Schema<IUserChats> = new Schema(
  {
    userId: {
      type: String,
      required: true,
    },
    chats: [
      {
        chatId: {
          type: String,
          required: true,
        },
        title: {
          type: String,
          required: true,
        },
        model: {
          type: Number, // <-- number (0 or 1)
          required: true,
        },
        createdAt: {
          type: Date,
          default: Date.now, // Ensure the function reference is used
        },
      },
      { _id: false }, // Disable _id for nested parts
    ],
  },
  { timestamps: true } // Automatically adds createdAt and updatedAt fields
);

// Define the model with type safety
const UserChats: Model<IUserChats> =
  mongoose.models.userchats || mongoose.model<IUserChats>("userchats", userChatsSchema);

export default UserChats;
